# Generated by Django 4.2.2 on 2023-06-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='professor',
            field=models.CharField(choices=[('professor1', 'Sandro'), ('professor2', 'Nilton'), ('professor3', 'Orlando')], max_length=100),
        ),
    ]
